import React, { useState } from 'react';
import { Calendar, Download, FileText, Pill, HelpCircle, Plus, Trash2, CheckCircle2, Printer, Sparkles, Building } from 'lucide-react';
import jsPDF from 'jspdf';
import confetti from 'canvas-confetti';

export default function DoctorVisitView({ documents }) {
  const [appointmentDate, setAppointmentDate] = useState("2026-10-15");
  const [doctorName, setDoctorName] = useState("Dr. Sarah Jenkins, MD");
  const [clinicName, setClinicName] = useState("Metro Health Internal Medicine");
  
  const [questions, setQuestions] = useState([
    "What do these latest lab results mean in my specific situation?",
    "Do I need any follow-up testing in 3 to 6 months?",
    "Should we compare my latest HbA1c and lipid results with my earlier January report?",
    "Are there any specific dietary or lifestyle instructions I should adjust?"
  ]);
  const [newQuestionText, setNewQuestionText] = useState('');

  // Extract recent documents & active meds
  const recentDocs = documents.slice(0, 3);
  const activeMeds = documents.flatMap(d => d.extractedData?.medications || []);

  const handleAddQuestion = () => {
    if (newQuestionText.trim()) {
      setQuestions([...questions, newQuestionText.trim()]);
      setNewQuestionText('');
    }
  };

  const handleRemoveQuestion = (idx) => {
    setQuestions(questions.filter((_, i) => i !== idx));
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    
    // PDF Styling
    doc.setFillColor(10, 15, 36); // Deep navy header
    doc.rect(0, 0, 210, 35, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("MedRef AI — Doctor Visit Appointment Brief", 14, 18);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Scheduled Date: ${appointmentDate} | Doctor: ${doctorName}`, 14, 27);
    
    // Reset body styling
    doc.setTextColor(30, 41, 59);
    let yPos = 45;

    // Section 1: Recent Documents
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("1. Recent Indexed Documents Summary", 14, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    recentDocs.forEach(d => {
      doc.text(`• ${d.date}: ${d.title} (${d.facility})`, 18, yPos);
      yPos += 6;
    });

    yPos += 6;

    // Section 2: Active Medications
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("2. Active Prescribed Medications", 14, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    activeMeds.forEach(m => {
      doc.text(`• ${m.name} ${m.dosage} — ${m.frequency} (${m.instructions})`, 18, yPos);
      yPos += 6;
    });

    yPos += 6;

    // Section 3: Questions to Discuss
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("3. Questions Prepared for Healthcare Provider", 14, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    questions.forEach((q, qIdx) => {
      doc.text(`[  ]  ${qIdx + 1}. ${q}`, 18, yPos);
      yPos += 7;
    });

    yPos += 12;
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text("Generated by MedRef AI for informational support. Verify all records with your doctor.", 14, yPos);

    doc.save(`MedRef_Appointment_Brief_${appointmentDate}.pdf`);
    confetti({ particleCount: 60, spread: 70, origin: { y: 0.6 } });
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fadeIn pb-12">
      {/* Title Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-300 text-xs font-semibold mb-2">
            <Calendar className="w-3.5 h-3.5" />
            <span>Consultation Preparation</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Prepare for My Appointment</h1>
          <p className="text-xs sm:text-sm text-slate-400 mt-1">
            Aggregate recent health records, medications, and custom discussion questions into a formatted doctor brief.
          </p>
        </div>

        <button
          onClick={handleExportPDF}
          className="px-5 py-3 rounded-xl bg-gradient-to-r from-cyan-500 via-blue-600 to-indigo-600 hover:from-cyan-400 hover:to-blue-500 text-white text-xs font-semibold shadow-lg shadow-cyan-500/20 flex items-center justify-center gap-2 self-start sm:self-auto"
        >
          <Download className="w-4 h-4" />
          <span>Export Appointment Brief (PDF)</span>
        </button>
      </div>

      {/* Appointment Setup Controls Card */}
      <div className="p-6 rounded-3xl bg-slate-900/80 border border-slate-800 space-y-4">
        <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-300">Appointment Details</h3>
        
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div>
            <label className="text-xs text-slate-400 font-medium block mb-1">Appointment Date</label>
            <input
              type="date"
              value={appointmentDate}
              onChange={(e) => setAppointmentDate(e.target.value)}
              className="w-full p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-slate-200 text-xs font-medium focus:border-cyan-500 focus:outline-none"
            />
          </div>

          <div>
            <label className="text-xs text-slate-400 font-medium block mb-1">Healthcare Professional</label>
            <input
              type="text"
              value={doctorName}
              onChange={(e) => setDoctorName(e.target.value)}
              className="w-full p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-slate-200 text-xs font-medium focus:border-cyan-500 focus:outline-none"
            />
          </div>

          <div>
            <label className="text-xs text-slate-400 font-medium block mb-1">Facility / Clinic</label>
            <input
              type="text"
              value={clinicName}
              onChange={(e) => setClinicName(e.target.value)}
              className="w-full p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-slate-200 text-xs font-medium focus:border-cyan-500 focus:outline-none"
            />
          </div>
        </div>
      </div>

      {/* Generated Appointment Brief Preview */}
      <div className="p-6 sm:p-8 rounded-3xl bg-slate-900/90 border border-slate-800 space-y-6 shadow-2xl">
        <div className="border-b border-slate-800 pb-4 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div>
            <span className="text-[10px] uppercase font-bold tracking-wider text-cyan-400 bg-cyan-500/10 px-2 py-0.5 rounded-full border border-cyan-500/20">
              Live Preview
            </span>
            <h2 className="text-xl font-bold text-white mt-1">Appointment Brief</h2>
            <p className="text-xs text-slate-400">Scheduled for {appointmentDate} with {doctorName} ({clinicName})</p>
          </div>
        </div>

        {/* Section 1: Recent Documents */}
        <div className="space-y-3">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-300 flex items-center gap-2">
            <FileText className="w-4 h-4 text-cyan-400" /> Recent Uploaded Medical Documents
          </h4>
          <div className="space-y-2">
            {recentDocs.map((doc) => (
              <div key={doc.id} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 text-xs flex items-center justify-between">
                <div>
                  <span className="font-semibold text-white">{doc.title}</span>
                  <span className="text-slate-400 ml-2">({doc.date})</span>
                </div>
                <span className="text-cyan-300 text-[11px] font-medium">{doc.facility}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Section 2: Active Medications */}
        <div className="space-y-3">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-300 flex items-center gap-2">
            <Pill className="w-4 h-4 text-emerald-400" /> Current Active Medication Summary
          </h4>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {activeMeds.map((med, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 text-xs space-y-0.5">
                <div className="font-semibold text-white">{med.name} — {med.dosage}</div>
                <div className="text-slate-400 text-[11px]">{med.frequency} ({med.instructions})</div>
              </div>
            ))}
          </div>
        </div>

        {/* Section 3: Questions to Discuss */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-300 flex items-center gap-2">
              <HelpCircle className="w-4 h-4 text-amber-400" /> Questions Prepared for Doctor
            </h4>
            <span className="text-[11px] text-slate-400">{questions.length} Questions</span>
          </div>

          <div className="space-y-2">
            {questions.map((q, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 text-xs flex items-center justify-between gap-3 group">
                <div className="flex items-start gap-2.5">
                  <span className="w-5 h-5 rounded-md bg-slate-900 border border-slate-700 text-cyan-400 font-bold text-[10px] flex items-center justify-center flex-shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <span className="text-slate-200 leading-relaxed">{q}</span>
                </div>
                <button
                  onClick={() => handleRemoveQuestion(idx)}
                  className="text-slate-500 hover:text-rose-400 p-1 rounded-lg transition-colors"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            ))}
          </div>

          {/* Add custom question input */}
          <div className="pt-2 flex items-center gap-2">
            <input
              type="text"
              placeholder="Add your own custom question to discuss..."
              value={newQuestionText}
              onChange={(e) => setNewQuestionText(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') handleAddQuestion(); }}
              className="flex-1 p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-slate-200 text-xs placeholder:text-slate-500 focus:border-cyan-500 focus:outline-none"
            />
            <button
              onClick={handleAddQuestion}
              className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-cyan-400 text-xs font-semibold flex items-center gap-1.5"
            >
              <Plus className="w-4 h-4" /> Add
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
